name: Swift

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@main
    - name: Install Requirements
      run: sudo apt-get -y update &&
           sudo apt-get install -y libcurl4-openssl-dev libmysqlclient-dev &&
           sudo sed -i -e 's/-fabi-version=2 -fno-omit-frame-pointer//g' /usr/lib/x86_64-linux-gnu/pkgconfig/mysqlclient.pc &&
           sudo cp /usr/bin/convert /usr/local/bin
    - name: Resolve
      run: swift package resolve
    - name: Build
      run: swift build --enable-test-discovery -Xswiftc -g -c debug
    - name: Test
      run: swift test --enable-test-discovery -Xswiftc -g -c debug
  Deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set .gitsha
      if: github.event_name == 'push'
      run: "echo ${{github.sha}} > .gitsha"
    - name: Set .gitref
      if: github.event_name == 'push'
      run: "echo ${{github.ref}} > .gitref"
    - name: Publish Version
      uses: 123FLO321/github-docker-temp@0.5.0
      if: github.event_name == 'push'
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Commit
      uses: 123FLO321/github-docker-temp@0.5.0
      if: github.event_name == 'push'
      with:
        imageTag: ${{ github.sha }}
        accessToken: ${{ secrets.GITHUB_TOKEN }}
