name: Swift

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@master
    - name: Install Requirements
      run: sudo apt-get update && sudo apt-get install -y libssl-dev libcurl4-openssl-dev libmysqlclient-dev uuid-dev imagemagick mysql-client-5.7 && sudo sed -i -e 's/-fabi-version=2 -fno-omit-frame-pointer//g' /usr/lib/x86_64-linux-gnu/pkgconfig/mysqlclient.pc && sudo cp /usr/bin/convert /usr/local/bin
    - name: Resolve
      run: swift package resolve
    - uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-debug-5-spm-${{ hashFiles('Package.resolved') }}
    - name: Build
      run: swift build --enable-test-discovery -Xswiftc -g -c debug
    - name: Test
      run: swift test --enable-test-discovery -Xswiftc -g -c debug
  Deploy:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Set .gitsha
      run: "echo ${{github.sha}} > .gitsha"
    - name: Set .gitref
      run: "echo ${{github.ref}} > .gitref"
    - name: Publish
      uses: 123FLO321/github-docker-temp@0.5.0
      if: github.event_name == 'push'
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: .github/docker/Dockerfile-localbuild-debug
  BuildRelease:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@master
    - name: Install Requirements
      run: sudo apt-get update && sudo apt-get install -y libssl-dev libcurl4-openssl-dev libmysqlclient-dev uuid-dev imagemagick mysql-client-5.7 && sudo sed -i -e 's/-fabi-version=2 -fno-omit-frame-pointer//g' /usr/lib/x86_64-linux-gnu/pkgconfig/mysqlclient.pc && sudo cp /usr/bin/convert /usr/local/bin
    - name: Resolve
      run: swift package resolve
    - uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-release-4.2-spm-${{ hashFiles('Package.resolved') }}
    - name: Build
      run: swift build -v -c release
    - name: Upload executeable
      uses: actions/upload-artifact@v1
      with:
        name: build-release
        path: .build/release/RealDeviceMap
  DeployRelease:
    runs-on: ubuntu-16.04
    needs: BuildRelease
    steps:
    - uses: actions/checkout@v2
    - name: Download executeable
      uses: actions/download-artifact@v1
      if: github.event_name == 'push'
      run: "echo ${{github.sha}} > .gitsha"
    - name: Set .gitref
      if: github.event_name == 'push'
      run: "echo ${{github.ref}} > .gitref"
    - name: Publish
      uses: 123FLO321/github-docker-temp@0.5.0
      if: github.event_name == 'push'
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: .github/docker/Dockerfile-localbuild-release
        imageTagSuffix: -release
